include: package:very_good_analysis/analysis_options.5.0.0.yaml
linter:
  rules:
    public_member_api_docs: false

    # We want to use a limit of 120 characters
    lines_longer_than_80_chars: false

analyzer:
  exclude:
    - "**/*.freezed.dart"
    - "**/*.g.dart"

formatter:
  line-length: 100
