name: manifiesto_mvp_app
description: Manifiesto MVP Flutter app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.19.1

dependencies:
  CleafyPlugin:
    path: ./packages/cleafy-plugin
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.3
  flutter_secure_storage: ^9.0.0
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  go_router: ^13.2.0
  google_fonts: ^6.1.0
  http: ^1.1.2
  intl: ^0.18.0
  json_annotation: ^4.6.0
  localizations:
    path: ./packages/localizations
  meta: ^1.9.1
  oauth2: ^2.0.2
  retrofit: ^4.0.3
  riverpod_annotation: ^2.2.1
  rxdart: ^0.27.7
  shared_preferences: ^2.2.1
  ui_kit:
    path: ./packages/ui_kit
  uuid: ^3.0.7
  webview_flutter: ^4.7.0
  wolt_modal_sheet: ^0.5.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.3.1
  mocktail: ^0.3.0
  retrofit_generator: ^8.0.6
  riverpod_generator: ^2.3.3
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/fonts/
