name: ui_kit
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ">=3.2.0-210.4.beta <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  app_settings: ^5.1.1
  dropdown_button2: ^2.3.9
  file_picker: ^8.0.3
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  localizations:
    path: ../localizations
  go_router: ^13.2.0
  google_fonts: ^6.1.0
  image_picker: ^1.1.1
  intl: ^0.18.0
  wolt_modal_sheet: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0

flutter:
  assets:
    - assets/icons/
    - assets/cards/
