arb-dir: lib/src/arb
template-arb-file: app_es.arb
output-class: AppLocalizations
output-dir: lib/src/l10n
output-localization-file: app_localizations.dart
nullable-getter: false
synthetic-package: false
